#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

infer run --fail-on-issue -- xcodebuild -project Teak.xcodeproj -sdk iphoneos -target Framework -configuration Release BUILD_DIR=./build OTHER_CFLAGS="-fembed-bitcode" clean build
retVal=$?
if [ ! $? -eq 0 ]; then
  exit $retVal
fi
(cd build/Release-iphoneos/; zip -y -r Teak.framework.zip Teak.framework/)
