#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

find ./Teak ./Sample ./Automated/Automated ./Automated/AutomatedTests ./Automated/AutomatedUITests \
  -path './Teak/3rdParty' -prune -o \
  -type f -name '*.[hm]' -print0 | xargs -0 clang-format -style=file -i
