#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [ "$(which aws)" == "" ]; then brew install awscli; fi
if [ "$(which clang-format)" == "" ]; then brew install clang-format; fi
if [ "$(which oclint-json-compilation-database)" == "" ]; then brew tap oclint/formulae; brew install oclint; fi
