platform :ios, '12.2'

target 'Automated' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Automated

  target 'AutomatedTests' do
    inherit! :search_paths
    use_frameworks!
    pod 'OCMockito', '~> 5.0'
  end

  target 'AutomatedUITests' do
    inherit! :search_paths
    use_frameworks!
    pod 'OCMockito', '~> 5.0'
  end

end
