platform :ios, '13.0'

target 'Automated' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Automated

  target 'AutomatedTests' do
    inherit! :search_paths
    use_frameworks!
    pod 'OCMockito', '~> 5.0'
  end

  target 'AutomatedUITests' do
    inherit! :search_paths
    use_frameworks!
    pod 'OCMockito', '~> 5.0'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
