version: 2
jobs:
  build:
    macos:
      xcode: "8.3.3"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - restore_cache:
          key: v0-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Fix 'Homebrew must be run under Ruby 2.3!'
          command: brew update
      - run:
          name: Homebrew Depenendcies
          command: ./setup
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          paths:
            - ~/Library/Caches/Homebrew/
            - vendor/bundle
          key: v0-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Validate Code Formatting
          command: ./validate-code-format
      - run:
          name: Import Teak Notification Category Data
          command: bundler exec import_notification_categories notification_categories.csv
      - run:
          name: Build Teak SDK
          command: ./compile
      - persist_to_workspace:
          root: .
          paths:
            - build/Release-iphoneos/Teak.framework.zip
            - build/Release-iphoneos/TeakResources.bundle.zip
            - TeakExtensions/TeakNotificationContent/Info.plist
  deploy:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: git fetch --tags
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - attach_workspace:
          at: workspace/
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp workspace/build/Release-iphoneos/Teak.framework.zip s3://teak-build-artifacts/ios/Teak$TEAK_DEPLOY_VERSION_STRING.framework.zip --acl public-read
            aws s3 cp workspace/build/Release-iphoneos/TeakResources.bundle.zip s3://teak-build-artifacts/ios/TeakResources$TEAK_DEPLOY_VERSION_STRING.bundle.zip --acl public-read
            aws s3 cp workspace/TeakExtensions/TeakNotificationContent/Info.plist s3://teak-build-artifacts/ios/Info$TEAK_DEPLOY_VERSION_STRING.plist --acl public-read
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      # Deploy versioned SDK to S3
      - deploy:
          requires:
            - build
          context: deploy-versioned
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      # Deploy 'latest' SDK to S3, requires manual approval
      - deploy:
          type: approval
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
