version: 2
jobs:
  test:
    macos:
      xcode: "10.2.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - ios-setup
      - run:
          name: Validate Code Formatting
          command: ./validate-code-format
      - run:
          name: Run Automated Tests
          command: ./test

  build:
    macos:
      xcode: "8.3.3"
    shell: /bin/bash --login -eo pipefail
    steps:
      - ios-setup
      - run:
          name: Build Teak SDK
          command: ./compile
      - persist_to_workspace:
          root: .
          paths:
            - build/Release-iphoneos/Teak.framework.zip
            - build/Release-iphoneos/TeakResources.bundle.zip
            - TeakExtensions/TeakNotificationContent/Info.plist
            - Sample/build/Release-iphoneos/TeakNotificationService.appex.zip
            - Sample/build/Release-iphoneos/TeakNotificationContent.appex.zip
            - TeakExtensions.zip

  deploy_versioned:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: git fetch --tags
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - attach_workspace:
          at: workspace/
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp workspace/build/Release-iphoneos/Teak.framework.zip s3://teak-build-artifacts/ios/Teak-$(git describe --tags --always).framework.zip --acl public-read
            aws s3 cp workspace/build/Release-iphoneos/TeakResources.bundle.zip s3://teak-build-artifacts/ios/TeakResources-$(git describe --tags --always).bundle.zip --acl public-read
            aws s3 cp workspace/TeakExtensions/TeakNotificationContent/Info.plist s3://teak-build-artifacts/ios/Info-$(git describe --tags --always).plist --acl public-read
            aws s3 cp workspace/Sample/build/Release-iphoneos/TeakNotificationService.appex.zip s3://teak-build-artifacts/ios/TeakNotificationService-$(git describe --tags --always).appex.zip --acl public-read
            aws s3 cp workspace/Sample/build/Release-iphoneos/TeakNotificationContent.appex.zip s3://teak-build-artifacts/ios/TeakNotificationContent-$(git describe --tags --always).appex.zip --acl public-read
            aws s3 cp workspace/TeakExtensions.zip s3://teak-build-artifacts/ios/TeakExtensions-$(git describe --tags --always).zip --acl public-read

  deploy_latest:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: git fetch --tags
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - attach_workspace:
          at: workspace/
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp workspace/build/Release-iphoneos/Teak.framework.zip s3://teak-build-artifacts/ios/Teak.framework.zip --acl public-read
            aws s3 cp workspace/build/Release-iphoneos/TeakResources.bundle.zip s3://teak-build-artifacts/ios/TeakResources.bundle.zip --acl public-read
            aws s3 cp workspace/TeakExtensions/TeakNotificationContent/Info.plist s3://teak-build-artifacts/ios/Info.plist --acl public-read
            aws s3 cp workspace/Sample/build/Release-iphoneos/TeakNotificationService.appex.zip s3://teak-build-artifacts/ios/TeakNotificationService.appex.zip --acl public-read
            aws s3 cp workspace/Sample/build/Release-iphoneos/TeakNotificationContent.appex.zip s3://teak-build-artifacts/ios/TeakNotificationContent.appex.zip --acl public-read
            aws s3 cp workspace/TeakExtensions.zip s3://teak-build-artifacts/ios/TeakExtensions.zip --acl public-read

workflows:
  version: 2
  un-tagged-build:
    jobs:
      - test:
          filters:
            tags:
              ignore: /.*/
      - build:
          filters:
            tags:
              ignore: /.*/
  tagged-build:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_versioned:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_latest:
          requires:
            - hold
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

commands:
  #
  # Common setup
  #
  ios-setup:
    description: "iOS Common Setup"
    steps:
      - checkout
      - run:
          shell: /bin/bash -eo pipefail
          name: Set Ruby Version 2.3
          command: echo "ruby-2.3" > .ruby-version
      - restore_cache:
          key: v1-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}-{{ .Environment.HOMEBREW_VERSION }}
      - run:
          name: Check Homebrew Version
          command: |
            echo "Checking for Homebrew version $HOMEBREW_VERSION"
            [ `brew --version | sed -n 1p | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'` = $HOMEBREW_VERSION ] || brew update
      - run:
          name: Homebrew Depenendcies
          command: HOMEBREW_NO_AUTO_UPDATE=1 ./setup
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          paths:
            - /usr/local/Homebrew/
            - ~/Library/Caches/Homebrew
            - vendor/bundle
            - Sample/vendor/bundle
          key: v1-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}-{{ .Environment.HOMEBREW_VERSION }}
      - add_ssh_keys:
          fingerprints:
            - "ab:48:b1:f2:a7:e9:0f:ba:81:3b:0c:16:48:6b:91:3d"
      - run:
          name: Import Teak Notification Category Data
          command: bundler exec import_notification_categories notification_categories.csv
